### PR TITLE
Pull in changes from CivicActions fork

### PR DESCRIPTION
**Pull request by xjensen**
A pull request to merge the changes we made during our Agile training.

Creating this PR because the master branch on the CivicActions fork seems to have many more commits than luke's previous PRs here.

### CODE REVIEW

**Comment by xjensen** [comment]
Hey OI friends (@JeffreyGarrett, @lukefretwell, @jdorothy), we created this PR to merge your changes from our Agile training last week back into our upstream repo. It's from the master branch on the CivicActions fork, which seemed to be the most recent. Hopefully this covers everything, but I wanted to check with y'all to see if we're missing anything. Thanks!

**Comment by lukefretwell** [comment]
@xjensen go for it. Note, you may need to fix the nav and homepage links, as they were throwing errors.

**Comment by xjensen** [comment]
Thanks, @lukefretwell!

**Comment by xjensen** [comment]
Closing this one in favor of PR #14 to include additional nav fixes.

**Pull request closed without merging**
